import { previewEncoding } from "./encoding.js";
import { AllProvidersRejectedError, HandoffUnknownError, IdempotencyConflictError, InvalidRecipientError, InvalidSenderError, ProviderRateLimitedError, ProviderRejectedError, SmsError, UnsupportedFieldError } from "./errors.js";
import { fingerprint } from "./idempotency.js";
import type { SmsClient, SmsClientOptions, SmsSendInput } from "./types.js";
const E164=/^\+[1-9]\d{1,14}$/;
function validateSender(from:SmsSendInput["from"]):boolean { if(!from)return true; if(typeof from==="string")return E164.test(from); if("senderId" in from)return /^[\x00-\x7F]{1,11}$/.test(from.senderId); if("shortCode" in from)return /^\d{4,8}$/.test(from.shortCode); return from.messagingService.length>0; }
export function createSmsClient(options:SmsClientOptions):SmsClient { if(options.adapters.length===0) throw new Error("At least one adapter is required"); const store=options.idempotencyStore; const fallback=options.fallback; return { validate(input){ const issues=[]; if(!E164.test(input.to)) issues.push({code:"invalid_recipient",message:"to must be a strict E.164 number",field:"to"}); if(!validateSender(input.from)) issues.push({code:"invalid_sender",message:"from is not a valid sender",field:"from"}); if(input.body.length===0) issues.push({code:"empty_body",message:"body must not be empty",field:"body"}); const p=previewEncoding(input.body); const candidates=options.adapters.filter(a=>!input.mediaUrls?.length||a.capabilities.mms).filter(a=>!input.sendAt||a.capabilities.scheduling).filter(a=>!input.webhookUrl||a.capabilities.deliveryReceipts).map(a=>a.name); if(input.mediaUrls?.length&&!candidates.length)issues.push({code:"unsupported_field",message:"MMS is not supported by configured adapters",field:"mediaUrls"}); if(input.sendAt&&!candidates.length)issues.push({code:"unsupported_field",message:"Scheduling is not supported by configured adapters",field:"sendAt"}); if(input.validityPeriodSec!==undefined)issues.push({code:"unsupported_field",message:"validityPeriodSec is not supported",field:"validityPeriodSec"}); if(input.webhookUrl&&!candidates.length)issues.push({code:"unsupported_field",message:"webhookUrl is not supported by configured adapters",field:"webhookUrl"}); return {...p,supported:issues.length===0&&candidates.length>0,issues,adapterCandidates:candidates}; }, capabilities(){return options.adapters.map(a=>({name:a.name,capabilities:a.capabilities}));}, async send(input,sendOptions={}) { const validation=this.validate(input); if(!validation.supported){const issue=validation.issues[0]; if(issue?.code==="invalid_recipient")throw new InvalidRecipientError(issue.message); if(issue?.code==="invalid_sender")throw new InvalidSenderError(issue.message); throw new UnsupportedFieldError(issue?.message??"No compatible adapter");} await options.beforeSend?.(input); const key=input.idempotencyKey; const fp=fingerprint(input); let reservationId:string|undefined; if(key&&store){ const r=await store.reserve(key,fp,options.idempotencyTtlSec??86400); if(r.kind==="conflict")throw new IdempotencyConflictError(); if(r.kind==="existing"){if(r.record.state==="accepted"&&r.record.result)return r.record.result; if(r.record.state==="unknown"||r.record.state==="reserved")throw new HandoffUnknownError(); if(r.record.state==="rejected")throw new ProviderRejectedError("Previously rejected",[]); reservationId=r.record.reservationId;} else reservationId=r.reservationId; }
 const attempted:string[]=[]; const failures:SmsError[]=[]; for(const adapter of options.adapters){ attempted.push(adapter.name); await options.hooks?.onAttempt?.({provider:adapter.name,attempt:attempted.length,input}); let outcome; try { outcome=await adapter.send(input,{signal:sendOptions.signal,attempt:attempted.length,idempotencyKey:key}); } catch(cause){ outcome={kind:"unknown" as const,message:"Provider request outcome is unknown",cause}; }
 if(outcome.kind==="accepted"){const result={id:crypto.randomUUID(),provider:adapter.name,providerId:outcome.providerId,delivery:outcome.delivery??"queued",handoff:"accepted" as const,encoding:validation.encoding,segments:validation.segments,attemptedProviders:[...attempted]}; if(key&&store&&reservationId)await store.finalize(key,reservationId,{fingerprint:fp,state:"accepted",result,expiresAt:Date.now()+86400000}); await options.hooks?.onAccepted?.(result); return result;}
 if(outcome.kind==="unknown"){const e=new HandoffUnknownError(outcome.message,attempted,outcome.cause); if(key&&store&&reservationId)await store.finalize(key,reservationId,{fingerprint:fp,state:"unknown",error:e,expiresAt:Date.now()+86400000}); await options.hooks?.onFailure?.({provider:adapter.name,error:e}); throw e;}
 const e=outcome.rateLimited?new ProviderRateLimitedError(outcome.message,outcome.retryAfter,attempted):new ProviderRejectedError(outcome.message,attempted,outcome.eligibleForFallback,outcome.status); failures.push(e); await options.hooks?.onFailure?.({provider:adapter.name,error:e}); if(!fallback||!outcome.eligibleForFallback)break; }
 if(key&&store&&reservationId)await store.finalize(key,reservationId,{fingerprint:fp,state:"rejected",error:failures.at(-1),expiresAt:Date.now()+86400000}); throw failures.length===1?failures[0]:new AllProvidersRejectedError(failures); }}; }
