export type SmsErrorCode = "invalid_recipient"|"invalid_sender"|"unsupported_field"|"provider_auth"|"provider_rejected"|"provider_rate_limited"|"handoff_unknown"|"idempotency_conflict"|"webhook_signature"|"all_providers_rejected";
export class SmsError extends Error { readonly code:SmsErrorCode; readonly retrySafe:boolean; readonly attemptedProviders:readonly string[]; constructor(message:string, code:SmsErrorCode, retrySafe:boolean, attemptedProviders:string[]=[], options?:{cause?:unknown}) { super(message,{cause:options?.cause}); this.name=this.constructor.name; this.code=code; this.retrySafe=retrySafe; this.attemptedProviders=[...attemptedProviders]; } }
export class InvalidRecipientError extends SmsError { constructor(message="Invalid recipient", attempted:string[]=[]){super(message,"invalid_recipient",false,attempted);} }
export class InvalidSenderError extends SmsError { constructor(message="Invalid sender", attempted:string[]=[]){super(message,"invalid_sender",false,attempted);} }
export class UnsupportedFieldError extends SmsError { constructor(message:string, attempted:string[]=[]){super(message,"unsupported_field",false,attempted);} }
export class ProviderAuthError extends SmsError { constructor(message:string, attempted:string[]=[]){super(message,"provider_auth",false,attempted);} }
export class ProviderRejectedError extends SmsError { readonly eligibleForFallback:boolean; readonly providerStatus?:number; constructor(message:string, attempted:string[]=[], eligible=false,status?:number){super(message,"provider_rejected",eligible,attempted);this.eligibleForFallback=eligible;this.providerStatus=status;} }
export class ProviderRateLimitedError extends SmsError { readonly retryAfter?:number; readonly eligibleForFallback=true; constructor(message:string,retryAfter?:number,attempted:string[]=[]){super(message,"provider_rate_limited",true,attempted);this.retryAfter=retryAfter;} }
export class HandoffUnknownError extends SmsError { constructor(message="SMS handoff outcome is unknown", attempted:string[]=[], cause?:unknown){super(message,"handoff_unknown",false,attempted,{cause});} }
export class IdempotencyConflictError extends SmsError { constructor(message="Idempotency key conflicts with a different payload", attempted:string[]=[]){super(message,"idempotency_conflict",false,attempted);} }
export class WebhookSignatureError extends SmsError { constructor(message="Invalid webhook signature"){super(message,"webhook_signature",false,[]);} }
export class AllProvidersRejectedError extends SmsError { readonly attempts:readonly SmsError[]; constructor(attempts:SmsError[]){super("All SMS providers rejected the send","all_providers_rejected",attempts.every(e=>e.retrySafe),attempts.flatMap(e=>e.attemptedProviders));this.attempts=attempts;} }
export function redact(value:unknown):unknown { if(typeof value!=="string") return value; return value.replace(/Bearer\s+[^\s]+/gi,"Bearer [REDACTED]").replace(/\+\d{7,15}/g,"+[REDACTED]"); }
